[package]
name = "easy-pl"
version = "1.0.0"
description = "Учёт состава и жеребьёвка осад для гильдии"
authors = ["SWDevStudio"]
edition = "2021"

[lib]
name = "easy_pl_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-sql = { version = "2.4.0", features = ["sqlite"] }
reqwest = { version = "0.13.4", features = ["json"] }
keyring = "4.1.6"
